name: Build Main

on:
  push:
    branches:
      - ealing
      
  workflow_dispatch:    

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: "Main - Build and Deploy"
    uses: ./.github/workflows/build-reusable.yaml
    secrets: inherit
    with:
      environment: ealing
